/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FlukierJupiter (https://sketchfab.com/FlukierJupiter)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/bcc69dacd1bc4eadaf4b9fc0d6e2430b
title: Book Open
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Book3({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/book3/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.18, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['BookOpen_LP_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/book3/scene.gltf')
