/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: madisparks (https://sketchfab.com/madisparks)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vintage-book-d3c4f7a1e0d6484a9b55cc7d8bd50108
title: Vintage Book
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/book1/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Book_Book_Mat_0.geometry} material={materials.Book_Mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/book1/scene.gltf')
