/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Thunder (https://sketchfab.com/thunderpwn)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/book-53a795bb587d4d49ac040aa4317ed7f7
title: Book
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/book2/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 3.46, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.19, 0.13, 0.03]}>
            <mesh geometry={nodes.Cube__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/book2/scene.gltf')
