/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JMDavis (https://sketchfab.com/hunbjorn)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/davisbasics-workboot-c2ca7ec60bbc4c8f8bca761c34448115
title: DavisBasics_WorkBoot
*/

import React, { useRef, useLayoutEffect, useEffect, useState} from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Boot({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/boots/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('Telephone');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI , 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.DavisBasics_LP_BootMaterial1_0.geometry} material={materials.BootMaterial1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/boots/scene.gltf')
