/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: berkgedik (https://sketchfab.com/berkgedik)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/metal-cabinet-low-poly-1053729ad9d24d71a578622251f76deb
title: Metal Cabinet (Low Poly)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cabinet({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/cabinet/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Kulp_Mentese} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Kapak} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Dolap} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/cabinet/scene.gltf')
