/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: oscarherry3d (https://sketchfab.com/oscarherry3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/fa90d82b9098424d9e32a51b529a8ea5
title: Clock
*/

import React, { useRef, useLayoutEffect, useEffect, useState } from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Clock({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/clock3/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('Clock');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI/2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.26, 0.97, 1.15]} rotation={[2.44, 0, 0]} scale={[0.06, 0.2, 3.02]}>
            <mesh
              geometry={nodes.pCube3_Hour_Minute_Second_0.geometry}
              material={nodes.pCube3_Hour_Minute_Second_0.material}
            />
          </group>
          <group rotation={[0, 0, -Math.PI / 2]} scale={[5.09, 0.16, 5.09]}>
            <mesh geometry={nodes.pCylinder4_Clock_0.geometry} material={materials.Clock} />
            <mesh geometry={nodes.pCylinder4_Edge_0.geometry} material={materials.Edge} />
          </group>
          <group position={[0.27, -0.02, -0.04]} rotation={[0, 0, -Math.PI / 2]} scale={[0.22, 0.02, 0.22]}>
            <mesh
              geometry={nodes.pCylinder5_Hour_Minute_Second_0.geometry}
              material={nodes.pCylinder5_Hour_Minute_Second_0.material}
            />
          </group>
          <group position={[0.26, -2.03, 0.77]} rotation={[-1.93, 0, 0]} scale={[0.06, 0.03, 4.38]}>
            <mesh
              geometry={nodes.pCube5_Hour_Minute_Second_0.geometry}
              material={nodes.pCube5_Hour_Minute_Second_0.material}
            />
          </group>
          <group position={[0.26, 1.65, -0.94]} rotation={[1.05, 0, 0]} scale={[0.06, 0.1, 3.82]}>
            <mesh
              geometry={nodes.pCube4_Hour_Minute_Second_0.geometry}
              material={nodes.pCube4_Hour_Minute_Second_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/clock3/scene.gltf')
