/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DMaesen (https://sketchfab.com/bumstrum)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/door-2738468b94d74c5f827e7e5df7be8359
title: Door
*/

import React, { useRef, useLayoutEffect, useEffect, useState } from 'react'
import { useGLTF, meshBounds } from '@react-three/drei'

export default function Door2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/door2/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('Telephone');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[74.32, -100.36, 0]}>
            <mesh geometry={nodes.frame_door1_0.geometry} material={nodes.frame_door1_0.material} />
          </group>
          <group position={[46.73, -112.94, 4.73]}>
            <group position={[-85.59, 0.56, -4.73]}>
              <mesh geometry={nodes.handle_door1_0.geometry} material={nodes.handle_door1_0.material} />
            </group>
            <mesh geometry={nodes.door_door1_0.geometry} material={nodes.door_door1_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/door2/scene.gltf')
