/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Grenzer029 (https://sketchfab.com/Grenzer029)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/f11284edee674533be7955666fd34c09
title: Heavy Metal Door
*/

import React, { useRef, useLayoutEffect, useEffect, useState } from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Door({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/door/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('Door');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.07, 0, 1.54]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Cylinder006_Door_0.geometry} material={materials.Door} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/door/scene.gltf')
