/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DisFUNny (https://sketchfab.com/3DisFUNny)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-golden-key-16c6d58a74764ef9a8bda39408bcf0b8
title: the Golden Key
*/

import React, { useRef, useLayoutEffect, useEffect, useState } from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Key({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/key/scene.gltf')
  const [hovered, setHover] = useState(false);
  useEffect(() => {
    if(hovered){
      alert('Telephone');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)}  ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 172.92]} scale={100}>
            <mesh geometry={nodes.Cylinder_Metal_0.geometry} material={materials.Metal} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/key/scene.gltf')
