/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Glitch5970 (https://sketchfab.com/Glitch5970)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fnaf-1-office-desk-0f7f9c8184324cb0974e219fef26a89c
title: FNaF 1 Office - DESK
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MetalDesk({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/metalDesk/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[4.59, 0.11, 1.64]}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.material} />
          </group>
          <group position={[-4.2, -1.8, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1.79, 0.11, 1.64]}>
            <mesh geometry={nodes.mesh_1.geometry} material={materials.material_1} />
          </group>
          <group position={[-2.1, -0.9, 0.45]} scale={[1, 0.83, 1]}>
            <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
          </group>
          <group position={[-2.1, -0.1, 0.45]} scale={[1, 0.83, 1]}>
            <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/metalDesk/scene.gltf')
