/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: CHooverShrimp (https://sketchfab.com/CHooverShrimp)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-broken-mirror-b5de0c9e3d4d49e684bc26db39b12f07
title: Old Broken Mirror
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mirror2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/mirror2/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.4}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials.DefaultMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/mirror2/scene.gltf')
