/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: artikora (https://sketchfab.com/artikor978)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sea-of-thieves-music-box-70de9ea240e84ad99c4f721c3cce251a
title: Sea of Thieves - Music Box
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function MusicBox({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../../../models/musicBox/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.34, 3.87, 0]} rotation={[-Math.PI, 1.3, -Math.PI]}>
            <group position={[0.26, 1.95, 0.22]} rotation={[-0.04, 0, 0.01]} scale={0.01}>
              <mesh geometry={nodes.Haut_lambert1_0.geometry} material={nodes.Haut_lambert1_0.material} />
            </group>
            <group position={[0.21, 1.03, -0.09]} scale={0.01}>
              <mesh geometry={nodes.Bas_lambert1_0.geometry} material={nodes.Bas_lambert1_0.material} />
            </group>
            <group position={[0.08, -0.15, 0.07]} scale={0.01}>
              <mesh geometry={nodes.Roue_2_lambert1_0.geometry} material={nodes.Roue_2_lambert1_0.material} />
            </group>
          </group>
          <group scale={0.01}>
            <mesh geometry={nodes.barre_lambert1_0.geometry} material={nodes.barre_lambert1_0.material} />
          </group>
          <group scale={0.01}>
            <mesh geometry={nodes.part1_lambert1_0.geometry} material={nodes.part1_lambert1_0.material} />
          </group>
          <group scale={0.01}>
            <mesh geometry={nodes.part2_lambert1_0.geometry} material={nodes.part2_lambert1_0.material} />
          </group>
          <group scale={0.01}>
            <mesh geometry={nodes.part5_lambert1_0.geometry} material={nodes.part5_lambert1_0.material} />
          </group>
          <group position={[0, 0, -12.58]} scale={0.01}>
            <mesh geometry={nodes.part6_lambert1_0.geometry} material={nodes.part6_lambert1_0.material} />
          </group>
          <group position={[-4.47, 6.96, 0]} scale={0.01}>
            <mesh geometry={nodes.part7_lambert1_0.geometry} material={nodes.part7_lambert1_0.material} />
          </group>
          <group position={[-0.07, 1.75, 6.98]} rotation={[0, 0, 1.95]} scale={0.01}>
            <mesh geometry={nodes.Clef_lambert1_0.geometry} material={nodes.Clef_lambert1_0.material} />
          </group>
          <group position={[0, 0.39, -9.79]} scale={0.01}>
            <mesh geometry={nodes.deco_4_lambert1_0.geometry} material={nodes.deco_4_lambert1_0.material} />
          </group>
          <group position={[-10.74, 9.51, -3.04]} rotation={[0, 0, 0.64]} scale={0.01}>
            <mesh geometry={nodes.deco_7_lambert1_0.geometry} material={nodes.deco_7_lambert1_0.material} />
          </group>
          <group position={[-8.73, 12.35, -1.63]} rotation={[0, 0, 0.61]} scale={0}>
            <mesh geometry={nodes.deco_8_lambert1_0.geometry} material={nodes.deco_8_lambert1_0.material} />
          </group>
          <group position={[-10.62, 11.87, -2.34]} rotation={[0, 0, 2.16]} scale={0}>
            <mesh geometry={nodes.deco_9_lambert1_0.geometry} material={nodes.deco_9_lambert1_0.material} />
          </group>
          <group position={[0, 0.39, 1.05]} scale={0.01}>
            <mesh geometry={nodes.deco_14_lambert1_0.geometry} material={nodes.deco_14_lambert1_0.material} />
          </group>
          <group position={[-10.81, 9.58, 1.94]} rotation={[0.04, 0.06, 0.62]} scale={0.01} />
          <group position={[-10.01, 10.03, 3.05]} rotation={[0.04, 0.06, 0.53]} scale={0.01} />
          <group position={[-12.93, 12.69, 4.2]} rotation={[1.56, 0.66, 0.11]} scale={0.01} />
          <group position={[-10.92, 14.52, 4.08]} rotation={[1.53, 0.02, -0.01]} scale={0.01} />
          <group position={[1.67, 0.47, -8.16]} rotation={[0, 0, -1.64]} scale={0.01} />
          <group position={[1.65, 1.26, -8.98]} rotation={[0, 0, -1.59]} scale={0.01} />
          <group position={[0.55, 1.26, -3.5]} rotation={[-1.59, Math.PI / 2, 0]} scale={0.01} />
          <group position={[-0.42, 0.33, -3.5]} rotation={[-1.59, Math.PI / 2, 0]} scale={0.01} />
          <group position={[-0.03, -0.02, 0]} scale={0.01}>
            <mesh geometry={nodes.barre_2_lambert1_0.geometry} material={nodes.barre_2_lambert1_0.material} />
          </group>
          <mesh geometry={nodes.polySurface27_lambert1_0.geometry} material={nodes.polySurface27_lambert1_0.material} />
          <group position={[0, 0, -0.04]}>
            <mesh geometry={nodes.polySurface2_lambert1_0.geometry} material={nodes.polySurface2_lambert1_0.material} />
          </group>
          <group position={[0, 0, -9.41]}>
            <mesh geometry={nodes.polySurface4_lambert1_0.geometry} material={nodes.polySurface4_lambert1_0.material} />
          </group>
          <group position={[0, 2.29, 0]} scale={[9.32, 4.77, 13.33]}>
            <mesh geometry={nodes.pCube2_lambert1_0.geometry} material={nodes.pCube2_lambert1_0.material} />
          </group>
          <group position={[-4.31, 8.59, 9.25]} rotation={[-1.58, -0.57, -0.51]}>
            <mesh
              geometry={nodes.polySurface32_lambert1_0.geometry}
              material={nodes.polySurface32_lambert1_0.material}
            />
          </group>
          <mesh geometry={nodes.polySurface17_lambert1_0.geometry} material={nodes.polySurface17_lambert1_0.material} />
          <mesh geometry={nodes.polySurface22_lambert1_0.geometry} material={nodes.polySurface22_lambert1_0.material} />
          <group position={[-0.02, 0, -0.07]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.polySurface7_lambert1_0.geometry} material={nodes.polySurface7_lambert1_0.material} />
            <mesh
              geometry={nodes.polySurface12_lambert1_0.geometry}
              material={nodes.polySurface12_lambert1_0.material}
            />
          </group>
          <mesh geometry={nodes.deco_23_lambert1_0.geometry} material={nodes.deco_23_lambert1_0.material} />
          <group position={[-6.2, -3.99, 0.04]} rotation={[Math.PI, 0, 2]}>
            <group position={[-0.9, -0.75, 0.55]} rotation={[0.02, -0.07, 0]}>
              <mesh
                geometry={nodes.polySurface33_lambert1_0.geometry}
                material={nodes.polySurface33_lambert1_0.material}
              />
            </group>
            <group position={[-0.28, -0.51, -0.19]} rotation={[-0.02, -0.05, 0]}>
              <mesh
                geometry={nodes.polySurface34_lambert1_0.geometry}
                material={nodes.polySurface34_lambert1_0.material}
              />
            </group>
            <group position={[-0.42, -0.39, 1.02]}>
              <mesh
                geometry={nodes.polySurface35_lambert1_0.geometry}
                material={nodes.polySurface35_lambert1_0.material}
              />
            </group>
            <group position={[-0.1, -0.69, 0.44]} rotation={[-0.14, 0.1, 0.01]}>
              <mesh
                geometry={nodes.polySurface36_lambert1_0.geometry}
                material={nodes.polySurface36_lambert1_0.material}
              />
            </group>
          </group>
          <group position={[-1.92, 0, 1.76]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.deco_30_lambert1_0.geometry} material={nodes.deco_30_lambert1_0.material} />
          <group position={[0, 0, -0.06]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.deco_31_lambert1_0.geometry} material={nodes.deco_31_lambert1_0.material} />
          </group>
          <group position={[0.11, 0, 0]}>
            <group position={[-0.04, 0, 0]} scale={0.01}>
              <mesh
                geometry={nodes.pasted__acier_lambert1_0.geometry}
                material={nodes.pasted__acier_lambert1_0.material}
              />
            </group>
            <group position={[-0.04, 0, 0]} scale={0.01}>
              <mesh
                geometry={nodes.pasted__rond_lambert1_0.geometry}
                material={nodes.pasted__rond_lambert1_0.material}
              />
            </group>
            <group position={[2.15, 1.84, -1.41]} rotation={[0, 0, -Math.PI / 2]} scale={0}>
              <mesh
                geometry={nodes.pasted__deco_5_lambert1_0.geometry}
                material={nodes.pasted__deco_5_lambert1_0.material}
              />
            </group>
            <group position={[2.15, 1.84, -4.17]} rotation={[0, 0, -Math.PI / 2]} scale={0}>
              <mesh
                geometry={nodes.pasted__deco_6_lambert1_0.geometry}
                material={nodes.pasted__deco_6_lambert1_0.material}
              />
            </group>
          </group>
          <group name="pasted__Roue" position={[-3.44, 4.17, 0]} rotation={[1.95, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.pasted__Roue_lambert1_0.geometry} material={nodes.pasted__Roue_lambert1_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/musicBox/scene.gltf')
