/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: I am Cassia (https://sketchfab.com/iamCassia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/papers-1356e831277647098c204be4b0edf65c
title: Papers
*/

import React, { useRef,  useLayoutEffect, useEffect, useState } from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Notes({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/notes/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('Notes');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes['2_2_0'].geometry} material={materials.material} />
          </group>
          <group position={[0, 0, -191.69]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes['3_3_0'].geometry} material={materials.material_1} />
          </group>
          <group position={[0, 0, -388.33]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes['4_4_0'].geometry} material={materials.material_2} />
          </group>
          <group position={[0, 0, 193.82]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes['1_1_0'].geometry} material={materials.material_3} />
          </group>
          <group position={[0, 0, -580.2]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes['5_6_0'].geometry} material={materials.material_4} />
          </group>
          <group position={[0, 0, -758.32]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes['6_5005_0'].geometry} material={materials['5.005']} />
          </group>
          <group position={[586.07, -0.07, -207.23]} rotation={[-Math.PI / 2, 0, 0.7]} scale={[77.64, 116.41, 134.76]}>
            <mesh geometry={nodes.Mix_3006_0.geometry} material={materials['3.006']} />
            <mesh geometry={nodes.Mix_1005_0.geometry} material={materials['1.005']} />
            <mesh geometry={nodes.Mix_2005_0.geometry} material={materials['2.005']} />
            <mesh geometry={nodes.Mix_3007_0.geometry} material={materials['3.007']} />
            <mesh geometry={nodes.Mix_4006_0.geometry} material={materials['4.006']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/notes/scene.gltf')
