/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: IUPUI Center for Digital Scholarship (https://sketchfab.com/iupuicds)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/4597faefaa984c07a4f7e0e32fd3ab02
title: Oil Painting of Peaches
*/

import React, { useCallback, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, a } from '@react-spring/three';

export default function Painting1({ ...props }) {
  const group = useRef()
  const mesh = useRef(null)
  const { nodes, materials } = useGLTF('../../../models/painting1/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, Math.PI , 0]}>
        <group position={[-39.62, 165.99, 206.86]} rotation={[0.61, 0.13, -0.04]}>
          <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
          <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
          <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
          <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
          <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
          <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
          <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
          <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
          <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
          <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
          <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} />
          <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} />
          <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} />
          <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} />
          <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} />
          <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/painting1/scene.gltf')
