/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/painting-by-zdzislaw-beksinski-3-11c1da576435418b800d50a942b77a6b
title: Painting by Zdzislaw Beksinski (3)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/painting2/scene.gltf')
  const clicker = (e) => {
    alert('I am click god');
  }
  return (
    <group scale={[0.15, 0.15, 0.15]} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.31, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['Plotno_1_-_painting_0'].geometry} material={materials['1_-_painting']} onClick={clicker}/>
            </group>
          </group>
          <group position={[0.16, 1.07, -0.04]} rotation={[-0.01, 0, -Math.PI]}>
            <mesh geometry={nodes['Maska_3_-_Back_0'].geometry} material={materials['3_-_Back']} />
          </group>
          <group position={[-0.16, 1.07, 0.04]} rotation={[-3.13, 0, 0]}>
            <mesh geometry={nodes.Szyba_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Rama01_LP_default_0.geometry} material={materials['default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/painting2/scene.gltf')
