/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ra3id (https://sketchfab.com/ra3id)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/upright-piano-ae0529d9da834820b8a9c30ec0b6228f
title: Upright Piano
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Piano({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/piano/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -67.74]}>
            <mesh geometry={nodes.polySurface4_lambert7_0.geometry} material={materials.lambert7} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/piano/scene.gltf')
