/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Valo Niskanen (https://sketchfab.com/Valo.Niskanen)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/old-tube-radio-6c40a15db4594a3296995776c71c175c
title: Old Tube Radio
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/radio/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.41, 0.79, 0.74]} rotation={[1.41, 0.02, 0.06]}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/radio/scene.gltf')
