/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KloWorks (https://sketchfab.com/kloworks)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rust-key-dbba2fadae1b48adb03c62123a4babcf
title: Rust key
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RustedKey({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/rustedKey/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.key1_low_phong2_0.geometry} material={materials.phong2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/rustedKey/scene.gltf')
