/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: vracolacus (https://sketchfab.com/vracolacus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-old-vintage-table-desk-wooden-table-c802441e808c4ae9a0cb1448ce3b6e82
title: Low Poly Old Vintage Table Desk - Wooden Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/table/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.stolik001} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.szuflada} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/table/scene.gltf')
