/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Prateek.Sharma (https://sketchfab.com/Prateek.Sharma)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wooden-table-8a5b41d6445c4f1fbefb2e4abfeebb0d
title: Wooden Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table3({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/table2/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[2.54, 2.54, 2.54]}>
            <group position={[0, 0, 44.31]}>
              <mesh geometry={nodes['Wooden_table_1_Material_#35_0'].geometry} material={materials.Material_35} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/table2/scene.gltf')
