/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jonathan Brown (https://sketchfab.com/Junders_Plunkett)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/retro-tv-ea7123d1875446b4a336abc653c55580
title: Retro TV
*/

import React, { useRef, useLayoutEffect, useEffect, useState } from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Television({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/television/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('TV');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.phong1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/television/scene.gltf')
