/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jonathan Brown (https://sketchfab.com/Junders_Plunkett)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/retro-tv-ea7123d1875446b4a336abc653c55580
title: Retro TV
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/television/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.phong1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/television/scene.gltf')
