/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: euanford12321 (https://sketchfab.com/euanford12321)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-telephone-e57825be6b8741899bdcea7c98d47eb9
title: Old Telephone
*/

import React, { useRef, useLayoutEffect, useEffect, useState} from 'react'
import { meshBounds, useGLTF } from '@react-three/drei'

export default function Telephone({ keyPressed, onHover, ...props }) {
  const group = useRef()
  const ref = useRef();

  const { nodes, materials } = useGLTF('../../../models/telephone/scene.gltf')
  const [hovered, setHover] = useState(false);

  useEffect(() => {
    if(hovered){
      alert('Telephone');
    }else{
      console.log('as');
    }
    // document.body.style.cursor = hovered ? "grab" : "auto";
  }, [hovered]);
  useLayoutEffect(
    () =>{
      for(let i = 0; i < nodes.length; i++){
        if(nodes[i].isMesh){
          nodes[i].raycast = meshBounds;
        }
      }
    },
    []
  );
  return (
    <group raycast={meshBounds} onPointerDown={(event) => setHover(true)} onPointerOut={(event) => setHover(false)} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 117, 7]}>
            <mesh geometry={nodes.Wood_Wood_0.geometry} material={materials.Wood} />
          </group>
          <group
            position={[99.3, -37.34, -0.15]}
            rotation={[Math.PI, Math.PI / 4, Math.PI / 2]}
            scale={[16.8, 7.95, 1.76]}>
            <mesh geometry={nodes.Feet_Feet_0.geometry} material={materials.Feet} />
          </group>
          <group position={[-49.16, 176.69, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[48.58, 48.58, 2.43]}>
            <mesh geometry={nodes.Phone_Phone_0.geometry} material={materials.Phone} />
          </group>
          <group position={[-48.49, 180.27, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[45.61, 45.61, 0.82]}>
            <mesh geometry={nodes.Dial_Numbers_Dial_Numbers_0.geometry} material={materials.Dial_Numbers} />
          </group>
          <group position={[0, 0, 246.61]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cable_Cable_0.geometry} material={materials.Cable} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../models/telephone/scene.gltf')
