/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Philipp Busse (https://sketchfab.com/WoTiger)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/damaged-wall-11616746d0ea4bd59a2d9cf9a2b2fdfa
title: Damaged Wall
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const wallClicked = () => {
    alert('Ive been clicked!');
  }
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../models/wall/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.Default_OBJ} />
      </group> 
    </group>
  )
}

useGLTF.preload('../../../models/wall/scene.gltf')
